# from database import db
import datetime
from marshmallow import Schema, fields, pre_load, validate, post_load
from flask_marshmallow import Marshmallow
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()
ma = Marshmallow()


class User(db.Model):
    """The User object that owns tasks."""
    __tablename__ = 'user'
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String, nullable=False)
    secretWord = db.Column(db.String, nullable=False)

    role = db.relationship("Role", uselist=False)
    children = db.relationship("Children", uselist=False)

    # def __init__(*args, **kwargs):
    #     """On construction, set date of creation."""
    #     db.Model.__init__(*args, **kwargs)


class Role(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    userId = db.Column(db.Integer, db.ForeignKey("user.id"), nullable=False)
    #    user = db.relationship(User, back_populates="role")
    permits = db.Column(db.String, nullable=True)


class Address(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    adressline = db.Column(db.String, nullable=False)
    city = db.Column(db.String, nullable=False)
    country = db.Column(db.String, nullable=False)
    postalCode = db.Column(db.String, nullable=False)
    province = db.Column(db.String, nullable=False)
    childrenId = db.Column(db.String, db.ForeignKey("children.id"), nullable=False)

    #   children = db.relationship("Children", back_populates="address")


class SonidosDeCosasYAnimales(db.Model):
    __tablename__ = 'sonidosDeCosasYAnimales'

    id = db.Column(db.Integer, primary_key=True)
    sectionAId = db.Column(db.Integer, db.ForeignKey("sectionA.id"), nullable=False)
    am = db.Column(db.Boolean, nullable=True)
    ay = db.Column(db.Boolean, nullable=True)
    bee_mee = db.Column(db.Boolean, nullable=True)
    cuaCua = db.Column(db.Boolean, nullable=True)
    guauGuau_baBau = db.Column(db.Boolean, nullable=True)
    miau = db.Column(db.Boolean, nullable=True)
    muu = db.Column(db.Boolean, nullable=True)
    pio_pio = db.Column(db.Boolean, nullable=True)
    pum = db.Column(db.Boolean, nullable=True)
    qui_qui_ri_qui = db.Column(db.Boolean, nullable=True)
    rum_rum = db.Column(db.Boolean, nullable=True)
    tu_tu = db.Column(db.Boolean, nullable=True)
    total = db.Column(db.Integer, nullable=True)


class AnimalesDeVerdadYDeJuguete(db.Model):
    __tablename__ = 'animalesDeVerdadYDeJuguete'

    id = db.Column(db.Integer, primary_key=True)
    sectionAId = db.Column(db.Integer, db.ForeignKey("sectionA.id"), nullable=False)
    abeja = db.Column(db.Boolean, nullable=True)
    animal = db.Column(db.Boolean, nullable=True)
    arana = db.Column(db.Boolean, nullable=True)
    ardilla = db.Column(db.Boolean, nullable=True)
    ballena = db.Column(db.Boolean, nullable=True)
    bicho = db.Column(db.Boolean, nullable=True)
    burro = db.Column(db.Boolean, nullable=True)
    caballo = db.Column(db.Boolean, nullable=True)
    cebra = db.Column(db.Boolean, nullable=True)
    chancho = db.Column(db.Boolean, nullable=True)
    ciervo_bambi = db.Column(db.Boolean, nullable=True)
    cocodrilo = db.Column(db.Boolean, nullable=True)
    conejo = db.Column(db.Boolean, nullable=True)
    cucaracha = db.Column(db.Boolean, nullable=True)
    elefante = db.Column(db.Boolean, nullable=True)
    foca = db.Column(db.Boolean, nullable=True)
    gallina = db.Column(db.Boolean, nullable=True)
    gato = db.Column(db.Boolean, nullable=True)
    gusano = db.Column(db.Boolean, nullable=True)
    hipopotamo = db.Column(db.Boolean, nullable=True)
    hormiga = db.Column(db.Boolean, nullable=True)
    jirafa = db.Column(db.Boolean, nullable=True)
    lechuza = db.Column(db.Boolean, nullable=True)
    leon = db.Column(db.Boolean, nullable=True)
    lobo = db.Column(db.Boolean, nullable=True)
    mariposa = db.Column(db.Boolean, nullable=True)
    mono = db.Column(db.Boolean, nullable=True)
    mosca = db.Column(db.Boolean, nullable=True)
    mosquito = db.Column(db.Boolean, nullable=True)
    oso = db.Column(db.Boolean, nullable=True)
    oveja = db.Column(db.Boolean, nullable=True)
    pajaro = db.Column(db.Boolean, nullable=True)
    pato = db.Column(db.Boolean, nullable=True)
    pavo = db.Column(db.Boolean, nullable=True)
    perro = db.Column(db.Boolean, nullable=True)
    pescado_pez = db.Column(db.Boolean, nullable=True)
    pinguino = db.Column(db.Boolean, nullable=True)
    pollito = db.Column(db.Boolean, nullable=True)
    rana = db.Column(db.Boolean, nullable=True)
    raton_rata = db.Column(db.Boolean, nullable=True)
    sapo = db.Column(db.Boolean, nullable=True)
    tigre = db.Column(db.Boolean, nullable=True)
    tortuga = db.Column(db.Boolean, nullable=True)
    vaca = db.Column(db.Boolean, nullable=True)
    vibora = db.Column(db.Boolean, nullable=True)
    total = db.Column(db.Integer, nullable=True)


class VehiculosDeVerdadYDeJuguete(db.Model):
    __tablename__ = 'vehiculosDeVerdadYDeJuguete'

    id = db.Column(db.Integer, primary_key=True)
    sectionAId = db.Column(db.Integer, db.ForeignKey("sectionA.id"), nullable=False)
    ambulancia = db.Column(db.Boolean, nullable=True)
    auto = db.Column(db.Boolean, nullable=True)
    autoPolicia = db.Column(db.Boolean, nullable=True)
    avion = db.Column(db.Boolean, nullable=True)
    barco = db.Column(db.Boolean, nullable=True)
    bicicleta_bici = db.Column(db.Boolean, nullable=True)
    camion = db.Column(db.Boolean, nullable=True)
    camionDeBomberos = db.Column(db.Boolean, nullable=True)
    cochecitoDeBebe = db.Column(db.Boolean, nullable=True)
    helicoptero = db.Column(db.Boolean, nullable=True)
    micro_colectivo = db.Column(db.Boolean, nullable=True)
    moto = db.Column(db.Boolean, nullable=True)
    tractor = db.Column(db.Boolean, nullable=True)
    tren = db.Column(db.Boolean, nullable=True)
    triciclo = db.Column(db.Boolean, nullable=True)
    taxi = db.Column(db.Boolean, nullable=True)
    total = db.Column(db.Integer, nullable=True)


class AlimentosYBebidas(db.Model):
    __tablename__ = 'alimentosYBebidas'

    id = db.Column(db.Integer, primary_key=True)
    sectionAId = db.Column(db.Integer, db.ForeignKey("sectionA.id"), nullable=False)
    total = db.Column(db.Integer, nullable=True)
    aceituna = db.Column(db.Boolean, nullable=True)
    agua = db.Column(db.Boolean, nullable=True)
    alfajor = db.Column(db.Boolean, nullable=True)
    arroz = db.Column(db.Boolean, nullable=True)
    atun = db.Column(db.Boolean, nullable=True)
    azucar = db.Column(db.Boolean, nullable=True)
    banana = db.Column(db.Boolean, nullable=True)
    cafe = db.Column(db.Boolean, nullable=True)
    calabaza = db.Column(db.Boolean, nullable=True)
    caramelo = db.Column(db.Boolean, nullable=True)
    carne = db.Column(db.Boolean, nullable=True)
    cereales = db.Column(db.Boolean, nullable=True)
    chicle = db.Column(db.Boolean, nullable=True)
    choclo = db.Column(db.Boolean, nullable=True)
    chocolatada = db.Column(db.Boolean, nullable=True)
    chocolate = db.Column(db.Boolean, nullable=True)
    chupetin = db.Column(db.Boolean, nullable=True)
    coca = db.Column(db.Boolean, nullable=True)
    comida_papa = db.Column(db.Boolean, nullable=True)
    dulce = db.Column(db.Boolean, nullable=True)
    durazno = db.Column(db.Boolean, nullable=True)
    empanada = db.Column(db.Boolean, nullable=True)
    fideos = db.Column(db.Boolean, nullable=True)
    frutilla = db.Column(db.Boolean, nullable=True)
    galletita = db.Column(db.Boolean, nullable=True)
    hamburguesa_paty = db.Column(db.Boolean, nullable=True)
    helado = db.Column(db.Boolean, nullable=True)
    hielo = db.Column(db.Boolean, nullable=True)
    huevo = db.Column(db.Boolean, nullable=True)
    jamon = db.Column(db.Boolean, nullable=True)
    jugo = db.Column(db.Boolean, nullable=True)
    leche = db.Column(db.Boolean, nullable=True)
    lentejas = db.Column(db.Boolean, nullable=True)
    licuado = db.Column(db.Boolean, nullable=True)
    limonada = db.Column(db.Boolean, nullable=True)
    mani = db.Column(db.Boolean, nullable=True)
    manteca = db.Column(db.Boolean, nullable=True)
    manzana = db.Column(db.Boolean, nullable=True)
    mate = db.Column(db.Boolean, nullable=True)
    melon = db.Column(db.Boolean, nullable=True)
    mermelada = db.Column(db.Boolean, nullable=True)
    milanesa = db.Column(db.Boolean, nullable=True)
    naranja = db.Column(db.Boolean, nullable=True)
    pan = db.Column(db.Boolean, nullable=True)
    papasFritas = db.Column(db.Boolean, nullable=True)
    papas = db.Column(db.Boolean, nullable=True)
    pescado = db.Column(db.Boolean, nullable=True)
    pizza = db.Column(db.Boolean, nullable=True)
    pochoclo = db.Column(db.Boolean, nullable=True)
    pollo = db.Column(db.Boolean, nullable=True)
    queso = db.Column(db.Boolean, nullable=True)
    sal = db.Column(db.Boolean, nullable=True)
    salchicha_pancho = db.Column(db.Boolean, nullable=True)
    salsa = db.Column(db.Boolean, nullable=True)
    sandia = db.Column(db.Boolean, nullable=True)
    soda_gaseosa = db.Column(db.Boolean, nullable=True)
    sopa = db.Column(db.Boolean, nullable=True)
    te = db.Column(db.Boolean, nullable=True)
    tomate = db.Column(db.Boolean, nullable=True)
    torta = db.Column(db.Boolean, nullable=True)
    tortilla = db.Column(db.Boolean, nullable=True)
    uvas = db.Column(db.Boolean, nullable=True)
    vainilla = db.Column(db.Boolean, nullable=True)
    yogurt = db.Column(db.Boolean, nullable=True)
    zanahoria = db.Column(db.Boolean, nullable=True)
    zapallo = db.Column(db.Boolean, nullable=True)


class RopaYAccesorios(db.Model):
    __tablename__ = 'ropaYAccesorios'

    id = db.Column(db.Integer, primary_key=True)
    sectionAId = db.Column(db.Integer, db.ForeignKey("sectionA.id"), nullable=False)
    total = db.Column(db.Integer, nullable=True)
    anteojos_lentes = db.Column(db.Boolean, nullable=True)
    aros = db.Column(db.Boolean, nullable=True)
    babero = db.Column(db.Boolean, nullable=True)
    bombacha = db.Column(db.Boolean, nullable=True)
    botas = db.Column(db.Boolean, nullable=True)
    boton = db.Column(db.Boolean, nullable=True)
    bufanda = db.Column(db.Boolean, nullable=True)
    buzo = db.Column(db.Boolean, nullable=True)
    calzoncillo = db.Column(db.Boolean, nullable=True)
    camisa = db.Column(db.Boolean, nullable=True)
    campera = db.Column(db.Boolean, nullable=True)
    cartera = db.Column(db.Boolean, nullable=True)
    cierre = db.Column(db.Boolean, nullable=True)
    collar = db.Column(db.Boolean, nullable=True)
    gorra_gorro = db.Column(db.Boolean, nullable=True)
    guantes = db.Column(db.Boolean, nullable=True)
    hebillla_gomita = db.Column(db.Boolean, nullable=True)
    malla = db.Column(db.Boolean, nullable=True)
    medias = db.Column(db.Boolean, nullable=True)
    mochila = db.Column(db.Boolean, nullable=True)
    ojotas = db.Column(db.Boolean, nullable=True)
    pantalon = db.Column(db.Boolean, nullable=True)
    panal = db.Column(db.Boolean, nullable=True)
    pijama = db.Column(db.Boolean, nullable=True)
    polera = db.Column(db.Boolean, nullable=True)
    pullover = db.Column(db.Boolean, nullable=True)
    remera = db.Column(db.Boolean, nullable=True)
    ropa = db.Column(db.Boolean, nullable=True)
    saco = db.Column(db.Boolean, nullable=True)
    shorts = db.Column(db.Boolean, nullable=True)
    sombrero = db.Column(db.Boolean, nullable=True)
    vestido = db.Column(db.Boolean, nullable=True)
    zapatilla = db.Column(db.Boolean, nullable=True)
    zapato = db.Column(db.Boolean, nullable=True)
    zapatilla = db.Column(db.Boolean, nullable=True)


class PartesDelCuerpo(db.Model):
    __tablename__ = 'partesDelCuerpo'

    id = db.Column(db.Integer, primary_key=True)
    sectionAId = db.Column(db.Integer, db.ForeignKey("sectionA.id"), nullable=False)
    total = db.Column(db.Integer, nullable=True)
    barba = db.Column(db.Boolean, nullable=True)
    bigote = db.Column(db.Boolean, nullable=True)
    boca = db.Column(db.Boolean, nullable=True)
    brazo = db.Column(db.Boolean, nullable=True)
    cabeza = db.Column(db.Boolean, nullable=True)
    cachete = db.Column(db.Boolean, nullable=True)
    cara = db.Column(db.Boolean, nullable=True)
    cola_culo = db.Column(db.Boolean, nullable=True)
    dedo = db.Column(db.Boolean, nullable=True)
    dientes = db.Column(db.Boolean, nullable=True)
    garganta_cuello = db.Column(db.Boolean, nullable=True)
    hombro = db.Column(db.Boolean, nullable=True)
    labios = db.Column(db.Boolean, nullable=True)
    lengua = db.Column(db.Boolean, nullable=True)
    mano = db.Column(db.Boolean, nullable=True)
    nariz = db.Column(db.Boolean, nullable=True)
    ojos = db.Column(db.Boolean, nullable=True)
    ombligo_pupo = db.Column(db.Boolean, nullable=True)
    oreja = db.Column(db.Boolean, nullable=True)
    panza = db.Column(db.Boolean, nullable=True)
    pecho_teta = db.Column(db.Boolean, nullable=True)
    pelo = db.Column(db.Boolean, nullable=True)
    pene_pito = db.Column(db.Boolean, nullable=True)
    piernas = db.Column(db.Boolean, nullable=True)
    pies_patas = db.Column(db.Boolean, nullable=True)
    rodilla = db.Column(db.Boolean, nullable=True)
    unas = db.Column(db.Boolean, nullable=True)
    vagina = db.Column(db.Boolean, nullable=True)


class Juguetes(db.Model):
    __tablename__ = 'juguetes'
    id = db.Column(db.Integer, primary_key=True)
    sectionAId = db.Column(db.Integer, db.ForeignKey("sectionA.id"), nullable=False)
    total = db.Column(db.Integer, nullable=True)
    birome_lapicera = db.Column(db.Boolean, nullable=True)
    bolitas = db.Column(db.Boolean, nullable=True)
    burbujas = db.Column(db.Boolean, nullable=True)
    crayones = db.Column(db.Boolean, nullable=True)
    cubos = db.Column(db.Boolean, nullable=True)
    fibras = db.Column(db.Boolean, nullable=True)
    globo = db.Column(db.Boolean, nullable=True)
    hoja_papel = db.Column(db.Boolean, nullable=True)
    juguete_chiche = db.Column(db.Boolean, nullable=True)
    lapiz = db.Column(db.Boolean, nullable=True)
    libro_cuento = db.Column(db.Boolean, nullable=True)
    muneca = db.Column(db.Boolean, nullable=True)
    osito = db.Column(db.Boolean, nullable=True)
    patines = db.Column(db.Boolean, nullable=True)
    pelicula_peli = db.Column(db.Boolean, nullable=True)
    pelota = db.Column(db.Boolean, nullable=True)
    peluche = db.Column(db.Boolean, nullable=True)
    pinturitas = db.Column(db.Boolean, nullable=True)
    plastilina = db.Column(db.Boolean, nullable=True)
    tambor = db.Column(db.Boolean, nullable=True)


class UtensillosDeLaCasa(db.Model):
    __tablename__ = 'utensillosDeLaCasa'

    id = db.Column(db.Integer, primary_key=True)
    sectionAId = db.Column(db.Integer, db.ForeignKey("sectionA.id"), nullable=False)
    total = db.Column(db.Integer, nullable=True)
    alfombra = db.Column(db.Boolean, nullable=True)
    almohada = db.Column(db.Boolean, nullable=True)
    balde = db.Column(db.Boolean, nullable=True)
    basura = db.Column(db.Boolean, nullable=True)
    bolsa_bolsita = db.Column(db.Boolean, nullable=True)
    botella = db.Column(db.Boolean, nullable=True)
    caja = db.Column(db.Boolean, nullable=True)
    camara = db.Column(db.Boolean, nullable=True)
    canasta = db.Column(db.Boolean, nullable=True)
    celular_celu = db.Column(db.Boolean, nullable=True)
    cepillo = db.Column(db.Boolean, nullable=True)
    cepilloDeDientes = db.Column(db.Boolean, nullable=True)
    champu = db.Column(db.Boolean, nullable=True)
    chupete = db.Column(db.Boolean, nullable=True)
    cigarrillos_puchos = db.Column(db.Boolean, nullable=True)
    clavos = db.Column(db.Boolean, nullable=True)
    cuadro = db.Column(db.Boolean, nullable=True)
    cuchara = db.Column(db.Boolean, nullable=True)
    cuchillo = db.Column(db.Boolean, nullable=True)
    diario = db.Column(db.Boolean, nullable=True)
    dinero_plata = db.Column(db.Boolean, nullable=True)
    escoba = db.Column(db.Boolean, nullable=True)
    espejo = db.Column(db.Boolean, nullable=True)
    fosforo = db.Column(db.Boolean, nullable=True)
    fotos = db.Column(db.Boolean, nullable=True)
    frazada = db.Column(db.Boolean, nullable=True)
    jabon = db.Column(db.Boolean, nullable=True)
    lampara = db.Column(db.Boolean, nullable=True)
    llave = db.Column(db.Boolean, nullable=True)
    luz = db.Column(db.Boolean, nullable=True)
    mamadera_meme = db.Column(db.Boolean, nullable=True)
    martillo = db.Column(db.Boolean, nullable=True)
    olla = db.Column(db.Boolean, nullable=True)
    panuelo = db.Column(db.Boolean, nullable=True)
    papel = db.Column(db.Boolean, nullable=True)
    pastaDeDientes = db.Column(db.Boolean, nullable=True)
    peine = db.Column(db.Boolean, nullable=True)
    pelela = db.Column(db.Boolean, nullable=True)
    plancha = db.Column(db.Boolean, nullable=True)
    plato = db.Column(db.Boolean, nullable=True)
    reloj = db.Column(db.Boolean, nullable=True)
    remedio = db.Column(db.Boolean, nullable=True)
    servilleta = db.Column(db.Boolean, nullable=True)
    tachoDeBasura = db.Column(db.Boolean, nullable=True)
    taza = db.Column(db.Boolean, nullable=True)
    telefono = db.Column(db.Boolean, nullable=True)
    tenedor = db.Column(db.Boolean, nullable=True)
    tijeras = db.Column(db.Boolean, nullable=True)
    toalla = db.Column(db.Boolean, nullable=True)
    trapo = db.Column(db.Boolean, nullable=True)
    vaso = db.Column(db.Boolean, nullable=True)
    vela = db.Column(db.Boolean, nullable=True)


class MueblesYCuartos(db.Model):
    __tablename__ = 'mueblesYCuartos'

    id = db.Column(db.Integer, primary_key=True)
    sectionAId = db.Column(db.Integer, db.ForeignKey("sectionA.id"), nullable=False)
    total = db.Column(db.Integer, nullable=True)
    banco = db.Column(db.Boolean, nullable=True)
    banadera = db.Column(db.Boolean, nullable=True)
    bano = db.Column(db.Boolean, nullable=True)
    bibloteca = db.Column(db.Boolean, nullable=True)
    cajon = db.Column(db.Boolean, nullable=True)
    cama = db.Column(db.Boolean, nullable=True)
    cochera_garage = db.Column(db.Boolean, nullable=True)
    cocina = db.Column(db.Boolean, nullable=True)
    computadora_compu = db.Column(db.Boolean, nullable=True)
    cuna = db.Column(db.Boolean, nullable=True)
    ducha = db.Column(db.Boolean, nullable=True)
    escaleras = db.Column(db.Boolean, nullable=True)
    estufa = db.Column(db.Boolean, nullable=True)
    habitacion_pieza = db.Column(db.Boolean, nullable=True)
    heladera = db.Column(db.Boolean, nullable=True)
    horno = db.Column(db.Boolean, nullable=True)
    inodoro = db.Column(db.Boolean, nullable=True)
    mesa = db.Column(db.Boolean, nullable=True)
    mueble = db.Column(db.Boolean, nullable=True)
    patio = db.Column(db.Boolean, nullable=True)
    piletaDeLavarManos = db.Column(db.Boolean, nullable=True)
    piso = db.Column(db.Boolean, nullable=True)
    placard = db.Column(db.Boolean, nullable=True)
    puerta = db.Column(db.Boolean, nullable=True)
    silla = db.Column(db.Boolean, nullable=True)
    sillon = db.Column(db.Boolean, nullable=True)
    television_tele = db.Column(db.Boolean, nullable=True)
    ventana = db.Column(db.Boolean, nullable=True)


class ObjetosFueraDeLaCasa(db.Model):
    __tablename__ = 'objetosFueraDeLaCasa'

    id = db.Column(db.Integer, primary_key=True)
    sectionAId = db.Column(db.Integer, db.ForeignKey("sectionA.id"), nullable=False)
    total = db.Column(db.Integer, nullable=True)
    arbol = db.Column(db.Boolean, nullable=True)
    arena = db.Column(db.Boolean, nullable=True)
    bandera = db.Column(db.Boolean, nullable=True)
    cielo = db.Column(db.Boolean, nullable=True)
    cucha = db.Column(db.Boolean, nullable=True)
    estrella = db.Column(db.Boolean, nullable=True)
    flor = db.Column(db.Boolean, nullable=True)
    fuego = db.Column(db.Boolean, nullable=True)
    hamaca = db.Column(db.Boolean, nullable=True)
    hojas = db.Column(db.Boolean, nullable=True)
    humo = db.Column(db.Boolean, nullable=True)
    lluvia = db.Column(db.Boolean, nullable=True)
    luna = db.Column(db.Boolean, nullable=True)
    maceta = db.Column(db.Boolean, nullable=True)
    manguera = db.Column(db.Boolean, nullable=True)
    nieve = db.Column(db.Boolean, nullable=True)
    nube = db.Column(db.Boolean, nullable=True)
    pala = db.Column(db.Boolean, nullable=True)
    palo = db.Column(db.Boolean, nullable=True)
    pasto = db.Column(db.Boolean, nullable=True)
    piedra = db.Column(db.Boolean, nullable=True)
    piletaNatacion_pile = db.Column(db.Boolean, nullable=True)
    planta = db.Column(db.Boolean, nullable=True)
    reja = db.Column(db.Boolean, nullable=True)
    sol = db.Column(db.Boolean, nullable=True)
    techo = db.Column(db.Boolean, nullable=True)
    tierra_barro = db.Column(db.Boolean, nullable=True)
    timbre = db.Column(db.Boolean, nullable=True)
    tobogan = db.Column(db.Boolean, nullable=True)
    viento_aire = db.Column(db.Boolean, nullable=True)


class LugaresFueraDeLaCasa(db.Model):
    __tablename__ = 'lugaresFueraDeLaCasa'

    id = db.Column(db.Integer, primary_key=True)
    sectionAId = db.Column(db.Integer, db.ForeignKey("sectionA.id"), nullable=False)
    total = db.Column(db.Integer, nullable=True)
    banco = db.Column(db.Boolean, nullable=True)
    bosque = db.Column(db.Boolean, nullable=True)
    calesita = db.Column(db.Boolean, nullable=True)
    calle = db.Column(db.Boolean, nullable=True)
    campo = db.Column(db.Boolean, nullable=True)
    casa = db.Column(db.Boolean, nullable=True)
    cerro_montana = db.Column(db.Boolean, nullable=True)
    circo = db.Column(db.Boolean, nullable=True)
    cumpleanos_cumple = db.Column(db.Boolean, nullable=True)
    escuela_cole = db.Column(db.Boolean, nullable=True)
    fiesta = db.Column(db.Boolean, nullable=True)
    hospital_clinica = db.Column(db.Boolean, nullable=True)
    iglesia_templo = db.Column(db.Boolean, nullable=True)
    jardin = db.Column(db.Boolean, nullable=True)
    mar = db.Column(db.Boolean, nullable=True)
    pelotero = db.Column(db.Boolean, nullable=True)
    playa = db.Column(db.Boolean, nullable=True)
    plaza = db.Column(db.Boolean, nullable=True)
    rio = db.Column(db.Boolean, nullable=True)
    supermercado_super = db.Column(db.Boolean, nullable=True)
    vereda = db.Column(db.Boolean, nullable=True)
    zoologico = db.Column(db.Boolean, nullable=True)


class Personas(db.Model):
    __tablename__ = 'personas'

    id = db.Column(db.Integer, primary_key=True)
    sectionAId = db.Column(db.Integer, db.ForeignKey("sectionA.id"), nullable=False)
    total = db.Column(db.Integer, nullable=True)
    abuela = db.Column(db.Boolean, nullable=True)
    abuelo = db.Column(db.Boolean, nullable=True)
    amiga = db.Column(db.Boolean, nullable=True)
    amigo = db.Column(db.Boolean, nullable=True)
    bebe = db.Column(db.Boolean, nullable=True)
    doctor = db.Column(db.Boolean, nullable=True)
    familia = db.Column(db.Boolean, nullable=True)
    hermana = db.Column(db.Boolean, nullable=True)
    hermano = db.Column(db.Boolean, nullable=True)
    madrina = db.Column(db.Boolean, nullable=True)
    maestra_seno = db.Column(db.Boolean, nullable=True)
    mama_mami = db.Column(db.Boolean, nullable=True)
    nina_nena = db.Column(db.Boolean, nullable=True)
    ninera = db.Column(db.Boolean, nullable=True)
    nino_nene = db.Column(db.Boolean, nullable=True)
    padrino = db.Column(db.Boolean, nullable=True)
    papa_papi = db.Column(db.Boolean, nullable=True)
    payaso = db.Column(db.Boolean, nullable=True)
    policia = db.Column(db.Boolean, nullable=True)
    prima = db.Column(db.Boolean, nullable=True)
    primo = db.Column(db.Boolean, nullable=True)
    senor = db.Column(db.Boolean, nullable=True)
    senora = db.Column(db.Boolean, nullable=True)
    policia = db.Column(db.Boolean, nullable=True)
    tia = db.Column(db.Boolean, nullable=True)
    tio = db.Column(db.Boolean, nullable=True)
    nombreDelInfante = db.Column(db.Boolean, nullable=True)


class RutinasReglasSocialesYJuegos(db.Model):
    __tablename__ = 'rutinasReglasSocialesYJuegos'

    id = db.Column(db.Integer, primary_key=True)
    sectionAId = db.Column(db.Integer, db.ForeignKey("sectionA.id"), nullable=False)
    total = db.Column(db.Integer, nullable=True)
    aVer_aPasear = db.Column(db.Boolean, nullable=True)
    adios_chau = db.Column(db.Boolean, nullable=True)
    ahiVoy = db.Column(db.Boolean, nullable=True)
    alAguaPatos = db.Column(db.Boolean, nullable=True)
    arribaLasManos = db.Column(db.Boolean, nullable=True)
    basta = db.Column(db.Boolean, nullable=True)
    besitos = db.Column(db.Boolean, nullable=True)
    buenasNoches = db.Column(db.Boolean, nullable=True)
    buenosDias = db.Column(db.Boolean, nullable=True)
    chasChas = db.Column(db.Boolean, nullable=True)
    cosquillita = db.Column(db.Boolean, nullable=True)
    cuco_acaEsta = db.Column(db.Boolean, nullable=True)
    dale = db.Column(db.Boolean, nullable=True)
    gol = db.Column(db.Boolean, nullable=True)
    gracias = db.Column(db.Boolean, nullable=True)
    hola = db.Column(db.Boolean, nullable=True)
    ojitos = db.Column(db.Boolean, nullable=True)
    perdon = db.Column(db.Boolean, nullable=True)
    pis = db.Column(db.Boolean, nullable=True)
    porFavor_porfi = db.Column(db.Boolean, nullable=True)
    pumba = db.Column(db.Boolean, nullable=True)
    queLindaManita = db.Column(db.Boolean, nullable=True)
    salud_chinChin = db.Column(db.Boolean, nullable=True)
    shhh = db.Column(db.Boolean, nullable=True)
    siesta_noniNoni = db.Column(db.Boolean, nullable=True)
    tortitas = db.Column(db.Boolean, nullable=True)
    unoDosTres = db.Column(db.Boolean, nullable=True)
    salud_chinChin = db.Column(db.Boolean, nullable=True)
    upa = db.Column(db.Boolean, nullable=True)
    vamos = db.Column(db.Boolean, nullable=True)
    vivaViva = db.Column(db.Boolean, nullable=True)
    yaEsta_listo = db.Column(db.Boolean, nullable=True)


class AccionesYProcesos(db.Model):
    __tablename__ = 'accionesYProcesos'

    id = db.Column(db.Integer, primary_key=True)
    sectionAId = db.Column(db.Integer, db.ForeignKey("sectionA.id"), nullable=False)
    total = db.Column(db.Integer, nullable=True)
    abrir = db.Column(db.Boolean, nullable=True)
    acabar = db.Column(db.Boolean, nullable=True)
    acompanar = db.Column(db.Boolean, nullable=True)
    acostar = db.Column(db.Boolean, nullable=True)
    agarrar = db.Column(db.Boolean, nullable=True)
    almorzar = db.Column(db.Boolean, nullable=True)
    andar = db.Column(db.Boolean, nullable=True)
    apagar = db.Column(db.Boolean, nullable=True)
    apurar = db.Column(db.Boolean, nullable=True)
    arreglar = db.Column(db.Boolean, nullable=True)
    asustar = db.Column(db.Boolean, nullable=True)
    atar = db.Column(db.Boolean, nullable=True)
    ayudar = db.Column(db.Boolean, nullable=True)
    bailar = db.Column(db.Boolean, nullable=True)
    bajar = db.Column(db.Boolean, nullable=True)
    banar = db.Column(db.Boolean, nullable=True)
    barrer = db.Column(db.Boolean, nullable=True)
    besar = db.Column(db.Boolean, nullable=True)
    buscar = db.Column(db.Boolean, nullable=True)
    caer = db.Column(db.Boolean, nullable=True)
    callar = db.Column(db.Boolean, nullable=True)
    caminar = db.Column(db.Boolean, nullable=True)
    cantar = db.Column(db.Boolean, nullable=True)
    cenar = db.Column(db.Boolean, nullable=True)
    cerrar = db.Column(db.Boolean, nullable=True)
    chupar = db.Column(db.Boolean, nullable=True)
    cocinar = db.Column(db.Boolean, nullable=True)
    comer = db.Column(db.Boolean, nullable=True)
    comprar = db.Column(db.Boolean, nullable=True)
    correr = db.Column(db.Boolean, nullable=True)
    cortar = db.Column(db.Boolean, nullable=True)
    dar = db.Column(db.Boolean, nullable=True)
    decir = db.Column(db.Boolean, nullable=True)
    dejar = db.Column(db.Boolean, nullable=True)
    desayunar = db.Column(db.Boolean, nullable=True)
    dibujar = db.Column(db.Boolean, nullable=True)
    doler = db.Column(db.Boolean, nullable=True)
    dormir = db.Column(db.Boolean, nullable=True)
    empujar = db.Column(db.Boolean, nullable=True)
    encontrar = db.Column(db.Boolean, nullable=True)
    ensenar = db.Column(db.Boolean, nullable=True)
    entrar = db.Column(db.Boolean, nullable=True)
    equivocar = db.Column(db.Boolean, nullable=True)
    esconder = db.Column(db.Boolean, nullable=True)
    escribir = db.Column(db.Boolean, nullable=True)
    escuchar = db.Column(db.Boolean, nullable=True)
    esperar = db.Column(db.Boolean, nullable=True)
    ganar = db.Column(db.Boolean, nullable=True)
    gritar = db.Column(db.Boolean, nullable=True)
    guardar = db.Column(db.Boolean, nullable=True)
    gustar = db.Column(db.Boolean, nullable=True)
    hablar = db.Column(db.Boolean, nullable=True)
    hacer = db.Column(db.Boolean, nullable=True)
    hamacar = db.Column(db.Boolean, nullable=True)
    ir = db.Column(db.Boolean, nullable=True)
    jugar = db.Column(db.Boolean, nullable=True)
    juntar = db.Column(db.Boolean, nullable=True)
    lastimar = db.Column(db.Boolean, nullable=True)
    lavar = db.Column(db.Boolean, nullable=True)
    leer = db.Column(db.Boolean, nullable=True)
    levantarse = db.Column(db.Boolean, nullable=True)
    llevar = db.Column(db.Boolean, nullable=True)
    llorar = db.Column(db.Boolean, nullable=True)
    meter = db.Column(db.Boolean, nullable=True)
    mirar = db.Column(db.Boolean, nullable=True)
    morder = db.Column(db.Boolean, nullable=True)
    mostrar = db.Column(db.Boolean, nullable=True)
    mover = db.Column(db.Boolean, nullable=True)
    nadar = db.Column(db.Boolean, nullable=True)
    oir = db.Column(db.Boolean, nullable=True)
    parar = db.Column(db.Boolean, nullable=True)
    patear = db.Column(db.Boolean, nullable=True)
    patinar = db.Column(db.Boolean, nullable=True)
    pegar = db.Column(db.Boolean, nullable=True)
    peinar = db.Column(db.Boolean, nullable=True)
    pensar = db.Column(db.Boolean, nullable=True)
    perder = db.Column(db.Boolean, nullable=True)
    pintar = db.Column(db.Boolean, nullable=True)
    poder = db.Column(db.Boolean, nullable=True)
    poner = db.Column(db.Boolean, nullable=True)
    prender = db.Column(db.Boolean, nullable=True)
    prestar = db.Column(db.Boolean, nullable=True)
    quedarse = db.Column(db.Boolean, nullable=True)
    quemarse = db.Column(db.Boolean, nullable=True)
    querer = db.Column(db.Boolean, nullable=True)
    quitar = db.Column(db.Boolean, nullable=True)
    regalar = db.Column(db.Boolean, nullable=True)
    respirar = db.Column(db.Boolean, nullable=True)
    romper = db.Column(db.Boolean, nullable=True)
    saber = db.Column(db.Boolean, nullable=True)
    sacar = db.Column(db.Boolean, nullable=True)
    salir = db.Column(db.Boolean, nullable=True)
    saltar = db.Column(db.Boolean, nullable=True)
    saludar = db.Column(db.Boolean, nullable=True)
    sentar = db.Column(db.Boolean, nullable=True)
    soplar = db.Column(db.Boolean, nullable=True)
    subir = db.Column(db.Boolean, nullable=True)
    tapar = db.Column(db.Boolean, nullable=True)
    tener = db.Column(db.Boolean, nullable=True)
    terminar = db.Column(db.Boolean, nullable=True)
    tirar = db.Column(db.Boolean, nullable=True)
    tocar = db.Column(db.Boolean, nullable=True)
    tomar = db.Column(db.Boolean, nullable=True)
    traer = db.Column(db.Boolean, nullable=True)
    venir = db.Column(db.Boolean, nullable=True)
    ver = db.Column(db.Boolean, nullable=True)
    volar = db.Column(db.Boolean, nullable=True)


class Estados(db.Model):
    __tablename__ = 'estados'

    id = db.Column(db.Integer, primary_key=True)
    sectionAId = db.Column(db.Integer, db.ForeignKey("sectionA.id"), nullable=False)
    total = db.Column(db.Integer, nullable=True)
    estar = db.Column(db.Boolean, nullable=True)
    haber_hay = db.Column(db.Boolean, nullable=True)
    ser = db.Column(db.Boolean, nullable=True)


class CualidadesYAtributos(db.Model):
    __tablename__ = 'cualidadesYAtributos'

    id = db.Column(db.Integer, primary_key=True)
    sectionAId = db.Column(db.Integer, db.ForeignKey("sectionA.id"), nullable=False)
    total = db.Column(db.Integer, nullable=True)
    alto = db.Column(db.Boolean, nullable=True)
    amarillo = db.Column(db.Boolean, nullable=True)
    asco_asqueroso = db.Column(db.Boolean, nullable=True)
    azul = db.Column(db.Boolean, nullable=True)
    blanco = db.Column(db.Boolean, nullable=True)
    bueno = db.Column(db.Boolean, nullable=True)
    caca_popo = db.Column(db.Boolean, nullable=True)
    caliente = db.Column(db.Boolean, nullable=True)
    cansado = db.Column(db.Boolean, nullable=True)
    chico_chiquitito = db.Column(db.Boolean, nullable=True)
    despierto = db.Column(db.Boolean, nullable=True)
    diferente_distinto = db.Column(db.Boolean, nullable=True)
    dificil = db.Column(db.Boolean, nullable=True)
    duro = db.Column(db.Boolean, nullable=True)
    enfermo = db.Column(db.Boolean, nullable=True)
    enojado = db.Column(db.Boolean, nullable=True)
    feliz = db.Column(db.Boolean, nullable=True)
    feo = db.Column(db.Boolean, nullable=True)
    frio = db.Column(db.Boolean, nullable=True)
    fuerte = db.Column(db.Boolean, nullable=True)
    gordo = db.Column(db.Boolean, nullable=True)
    grande = db.Column(db.Boolean, nullable=True)
    hambre = db.Column(db.Boolean, nullable=True)
    igual = db.Column(db.Boolean, nullable=True)
    largo = db.Column(db.Boolean, nullable=True)
    lento = db.Column(db.Boolean, nullable=True)
    limpio = db.Column(db.Boolean, nullable=True)
    lindo = db.Column(db.Boolean, nullable=True)
    loco = db.Column(db.Boolean, nullable=True)
    lleno = db.Column(db.Boolean, nullable=True)
    malo = db.Column(db.Boolean, nullable=True)
    mejor = db.Column(db.Boolean, nullable=True)
    mentiroso = db.Column(db.Boolean, nullable=True)
    miedo_susto = db.Column(db.Boolean, nullable=True)
    mojado = db.Column(db.Boolean, nullable=True)
    mugriento = db.Column(db.Boolean, nullable=True)
    negro = db.Column(db.Boolean, nullable=True)
    nuevo = db.Column(db.Boolean, nullable=True)
    oscuro = db.Column(db.Boolean, nullable=True)
    peligroso = db.Column(db.Boolean, nullable=True)
    pesado = db.Column(db.Boolean, nullable=True)
    pobre = db.Column(db.Boolean, nullable=True)
    primero = db.Column(db.Boolean, nullable=True)
    rapido = db.Column(db.Boolean, nullable=True)
    rico = db.Column(db.Boolean, nullable=True)
    rojo = db.Column(db.Boolean, nullable=True)
    rosa = db.Column(db.Boolean, nullable=True)
    roto = db.Column(db.Boolean, nullable=True)
    ruidoso = db.Column(db.Boolean, nullable=True)
    seco = db.Column(db.Boolean, nullable=True)
    solo = db.Column(db.Boolean, nullable=True)
    suave = db.Column(db.Boolean, nullable=True)
    sucio = db.Column(db.Boolean, nullable=True)
    tranquilo = db.Column(db.Boolean, nullable=True)
    tonto_bobo = db.Column(db.Boolean, nullable=True)
    triste = db.Column(db.Boolean, nullable=True)
    ultimo = db.Column(db.Boolean, nullable=True)
    vacio = db.Column(db.Boolean, nullable=True)
    verde = db.Column(db.Boolean, nullable=True)
    viejo = db.Column(db.Boolean, nullable=True)
    violeta = db.Column(db.Boolean, nullable=True)


class PalabrasSobreElTiempo(db.Model):
    __tablename__ = 'palabrasSobreElTiempo'

    id = db.Column(db.Integer, primary_key=True)
    sectionAId = db.Column(db.Integer, db.ForeignKey("sectionA.id"), nullable=False)
    total = db.Column(db.Integer, nullable=True)
    aLaManana = db.Column(db.Boolean, nullable=True)
    aLaNoche = db.Column(db.Boolean, nullable=True)
    aLaTarde = db.Column(db.Boolean, nullable=True)
    ahora = db.Column(db.Boolean, nullable=True)
    anos = db.Column(db.Boolean, nullable=True)
    ayer = db.Column(db.Boolean, nullable=True)
    despues = db.Column(db.Boolean, nullable=True)
    dia = db.Column(db.Boolean, nullable=True)
    hoy = db.Column(db.Boolean, nullable=True)
    manana = db.Column(db.Boolean, nullable=True)
    noche = db.Column(db.Boolean, nullable=True)


class PronombresYModificadores(db.Model):
    __tablename__ = 'pronombresYModificadores'

    id = db.Column(db.Integer, primary_key=True)
    sectionAId = db.Column(db.Integer, db.ForeignKey("sectionA.id"), nullable=False)
    total = db.Column(db.Integer, nullable=True)
    aquel = db.Column(db.Boolean, nullable=True)
    aquellos = db.Column(db.Boolean, nullable=True)
    aquella = db.Column(db.Boolean, nullable=True)
    aquellas = db.Column(db.Boolean, nullable=True)
    el = db.Column(db.Boolean, nullable=True)
    ellos = db.Column(db.Boolean, nullable=True)
    ella = db.Column(db.Boolean, nullable=True)
    ellas = db.Column(db.Boolean, nullable=True)
    esa = db.Column(db.Boolean, nullable=True)
    esas = db.Column(db.Boolean, nullable=True)
    ese = db.Column(db.Boolean, nullable=True)
    eso = db.Column(db.Boolean, nullable=True)
    esos = db.Column(db.Boolean, nullable=True)
    esta = db.Column(db.Boolean, nullable=True)
    estas = db.Column(db.Boolean, nullable=True)
    este = db.Column(db.Boolean, nullable=True)
    esto = db.Column(db.Boolean, nullable=True)
    estos = db.Column(db.Boolean, nullable=True)
    le = db.Column(db.Boolean, nullable=True)
    les = db.Column(db.Boolean, nullable=True)
    lo = db.Column(db.Boolean, nullable=True)
    me = db.Column(db.Boolean, nullable=True)
    mi = db.Column(db.Boolean, nullable=True)
    mia = db.Column(db.Boolean, nullable=True)
    mias = db.Column(db.Boolean, nullable=True)
    mio = db.Column(db.Boolean, nullable=True)
    mios = db.Column(db.Boolean, nullable=True)
    nosotros = db.Column(db.Boolean, nullable=True)
    nuestro = db.Column(db.Boolean, nullable=True)
    se = db.Column(db.Boolean, nullable=True)
    su = db.Column(db.Boolean, nullable=True)
    suya = db.Column(db.Boolean, nullable=True)
    suyas = db.Column(db.Boolean, nullable=True)
    suyo = db.Column(db.Boolean, nullable=True)
    suyos = db.Column(db.Boolean, nullable=True)
    te = db.Column(db.Boolean, nullable=True)
    tu = db.Column(db.Boolean, nullable=True)
    tuya = db.Column(db.Boolean, nullable=True)
    tuyas = db.Column(db.Boolean, nullable=True)
    tuyo = db.Column(db.Boolean, nullable=True)
    tuyos = db.Column(db.Boolean, nullable=True)
    vos = db.Column(db.Boolean, nullable=True)
    yo = db.Column(db.Boolean, nullable=True)


class Preguntas(db.Model):
    __tablename__ = 'preguntas'

    id = db.Column(db.Integer, primary_key=True)
    sectionAId = db.Column(db.Integer, db.ForeignKey("sectionA.id"), nullable=False)
    total = db.Column(db.Integer, nullable=True)
    como = db.Column(db.Boolean, nullable=True)
    cual = db.Column(db.Boolean, nullable=True)
    cuando = db.Column(db.Boolean, nullable=True)
    donde = db.Column(db.Boolean, nullable=True)
    porQue = db.Column(db.Boolean, nullable=True)
    que = db.Column(db.Boolean, nullable=True)
    quien = db.Column(db.Boolean, nullable=True)


class PreposicionesYArticulos(db.Model):
    __tablename__ = 'preposicionesYArticulos'

    id = db.Column(db.Integer, primary_key=True)
    sectionAId = db.Column(db.Integer, db.ForeignKey("sectionA.id"), nullable=False)
    total = db.Column(db.Integer, nullable=True)
    a_al = db.Column(db.Boolean, nullable=True)
    con = db.Column(db.Boolean, nullable=True)
    de_del = db.Column(db.Boolean, nullable=True)
    el = db.Column(db.Boolean, nullable=True)
    en = db.Column(db.Boolean, nullable=True)
    entre = db.Column(db.Boolean, nullable=True)
    la = db.Column(db.Boolean, nullable=True)
    las = db.Column(db.Boolean, nullable=True)
    los = db.Column(db.Boolean, nullable=True)
    para = db.Column(db.Boolean, nullable=True)
    pero = db.Column(db.Boolean, nullable=True)
    un = db.Column(db.Boolean, nullable=True)
    una = db.Column(db.Boolean, nullable=True)
    unas = db.Column(db.Boolean, nullable=True)
    unos = db.Column(db.Boolean, nullable=True)


class CuantificadoresYAdverbios(db.Model):
    __tablename__ = 'cuantificadoresYAdverbios'

    id = db.Column(db.Integer, primary_key=True)
    sectionAId = db.Column(db.Integer, db.ForeignKey("sectionA.id"), nullable=False)
    total = db.Column(db.Integer, nullable=True)
    asi = db.Column(db.Boolean, nullable=True)
    bien = db.Column(db.Boolean, nullable=True)
    despacio = db.Column(db.Boolean, nullable=True)
    mal = db.Column(db.Boolean, nullable=True)
    mas = db.Column(db.Boolean, nullable=True)
    mucho = db.Column(db.Boolean, nullable=True)
    nada = db.Column(db.Boolean, nullable=True)
    no = db.Column(db.Boolean, nullable=True)
    noHay = db.Column(db.Boolean, nullable=True)
    otro_otraVez = db.Column(db.Boolean, nullable=True)
    poco_poquito = db.Column(db.Boolean, nullable=True)
    rapido = db.Column(db.Boolean, nullable=True)
    si = db.Column(db.Boolean, nullable=True)
    todavia = db.Column(db.Boolean, nullable=True)
    todo = db.Column(db.Boolean, nullable=True)
    ya = db.Column(db.Boolean, nullable=True)


class Locativos(db.Model):
    __tablename__ = 'locativos'

    id = db.Column(db.Integer, primary_key=True)
    sectionAId = db.Column(db.Integer, db.ForeignKey("sectionA.id"), nullable=False)
    total = db.Column(db.Integer, nullable=True)
    abajo = db.Column(db.Boolean, nullable=True)
    aca = db.Column(db.Boolean, nullable=True)
    adelante = db.Column(db.Boolean, nullable=True)
    adentro = db.Column(db.Boolean, nullable=True)
    afuera = db.Column(db.Boolean, nullable=True)
    ahi = db.Column(db.Boolean, nullable=True)
    alla = db.Column(db.Boolean, nullable=True)
    alLado = db.Column(db.Boolean, nullable=True)
    aqui = db.Column(db.Boolean, nullable=True)
    arriba = db.Column(db.Boolean, nullable=True)
    atras = db.Column(db.Boolean, nullable=True)
    cerca = db.Column(db.Boolean, nullable=True)
    enfrente = db.Column(db.Boolean, nullable=True)
    lejos = db.Column(db.Boolean, nullable=True)


class Conectivos(db.Model):
    __tablename__ = 'conectivos'

    id = db.Column(db.Integer, primary_key=True)
    sectionAId = db.Column(db.Integer, db.ForeignKey("sectionA.id"), nullable=False)
    total = db.Column(db.Integer, nullable=True)
    entonces = db.Column(db.Boolean, nullable=True)
    o = db.Column(db.Boolean, nullable=True)
    porque = db.Column(db.Boolean, nullable=True)
    que = db.Column(db.Boolean, nullable=True)
    si = db.Column(db.Boolean, nullable=True)
    sino = db.Column(db.Boolean, nullable=True)
    tambien = db.Column(db.Boolean, nullable=True)
    y = db.Column(db.Boolean, nullable=True)


class Context(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    childrenQuantity = db.Column(db.Integer, nullable=True)
    familyGroup = db.Column(db.String, nullable=True)
    childKeeper = db.Column(db.String, nullable=True)
    anotherChildKeeper = db.Column(db.String, nullable=True)
    kinderGarten = db.Column(db.Boolean, nullable=False)
    kinderGartenHoursPerDay = db.Column(db.Boolean, nullable=False)
    kinderGartenHoursPerWeek = db.Column(db.Boolean, nullable=False)
    languanguesContact = db.Column(db.Boolean, nullable=False)
    languangues = db.Column(db.String, nullable=True)
    languanguesAge = db.Column(db.Integer, nullable=True)
    educationTutor1 = db.Column(db.String, nullable=True)
    ocupationTutor1 = db.Column(db.String, nullable=True)
    educationTutor2 = db.Column(db.String, nullable=True)
    ocupationTutor2 = db.Column(db.String, nullable=True)
    childrenId = db.Column(db.Integer, db.ForeignKey("children.id"), nullable=False)


class Survey(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    finished = db.Column(db.Boolean, nullable=False, default=False)
    creationDate = db.Column(db.DateTime, nullable=True)
    childrenId = db.Column(db.Integer, db.ForeignKey("children.id"), nullable=False)
    name = db.Column(db.String, nullable=True)
    dni = db.Column(db.Integer, nullable=True)
    gender = db.Column(db.String, nullable=True)
    birthday = db.Column(db.Date, nullable=True)
    age = db.Column(db.Integer, nullable=True)
    total = db.Column(db.Integer, nullable=True)
    #   children = db.relationship("Children", back_populates="children")

    sectionA = db.relationship("SectionA")
    results = db.relationship("Results")


class SectionA(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    surveyId = db.Column(db.Integer, db.ForeignKey("survey.id"), nullable=False)
    accionesYProcesos = db.relationship("AccionesYProcesos")
    alimentosYBebidas = db.relationship("AlimentosYBebidas")
    animalesDeVerdadYDeJuguete = db.relationship("AnimalesDeVerdadYDeJuguete")
    conectivos = db.relationship("Conectivos")
    cualidadesYAtributos = db.relationship("CualidadesYAtributos")
    cuantificadoresYAdverbios = db.relationship("CuantificadoresYAdverbios")
    estados = db.relationship("Estados")
    juguetes = db.relationship("Juguetes")
    locativos = db.relationship("Locativos")
    lugaresFueraDeLaCasa = db.relationship("LugaresFueraDeLaCasa")
    mueblesYCuartos = db.relationship("MueblesYCuartos")
    objetosFueraDeLaCasa = db.relationship("ObjetosFueraDeLaCasa")
    palabrasSobreElTiempo = db.relationship("PalabrasSobreElTiempo")
    partesDelCuerpo = db.relationship("PartesDelCuerpo")
    personas = db.relationship("Personas")
    preguntas = db.relationship("Preguntas")
    preposicionesYArticulos = db.relationship("PreposicionesYArticulos")
    pronombresYModificadores = db.relationship("PronombresYModificadores")
    ropaYAccesorios = db.relationship("RopaYAccesorios")
    rutinasReglasSocialesYJuegos = db.relationship("RutinasReglasSocialesYJuegos")
    sonidosDeCosasYAnimales = db.relationship("SonidosDeCosasYAnimales")
    utensillosDeLaCasa = db.relationship("UtensillosDeLaCasa")
    vehiculosDeVerdadYDeJuguete = db.relationship("VehiculosDeVerdadYDeJuguete")


class Children(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String, nullable=True)
    dni = db.Column(db.Integer, nullable=True)
    age = db.Column(db.Integer, nullable=True)
    birthday = db.Column(db.Date, nullable=True)
    birthPlace = db.Column(db.String, nullable=True)
    gender = db.Column(db.String, nullable=True)
    nameTutor1 = db.Column(db.String, nullable=True)
    nameTutor2 = db.Column(db.String, nullable=True)
    birthOrder = db.Column(db.Integer, nullable=True)
    premature = db.Column(db.Boolean, nullable=True)
    gestationWeeks = db.Column(db.Integer, nullable=True)
    birthWeight = db.Column(db.Integer, nullable=True)
    hearingDisease = db.Column(db.Boolean, nullable=True)
    descriptionDisease = db.Column(db.String, nullable=True)
    birthPlaceTutor1 = db.Column(db.String, nullable=True)
    birthPlaceTutor2 = db.Column(db.String, nullable=True)

    childrenQuantity = db.Column(db.Integer, nullable=True)
    familyGroup = db.Column(db.String, nullable=True)
    childKeeper = db.Column(db.String, nullable=True)
    anotherChildKeeper = db.Column(db.String, nullable=True)

    kinderGarden = db.Column(db.Boolean, nullable=True)
    kinderGardenHoursPerDay = db.Column(db.Integer, nullable=True)
    kinderGardenHoursPerWeek = db.Column(db.Integer, nullable=True)
    kinderGardenSince = db.Column(db.String, nullable=True)
    languangesContact = db.Column(db.Boolean, nullable=True)
    languanges = db.Column(db.String, nullable=True)
    languangesAge = db.Column(db.Integer, nullable=True)
    languangeSpeaker = db.Column(db.String, nullable=True)

    educationTutor1 = db.Column(db.String, nullable=True)
    ocupationTutor1 = db.Column(db.String, nullable=True)
    educationTutor2 = db.Column(db.String, nullable=True)
    ocupationTutor2 = db.Column(db.String, nullable=True)
    anyDisease = db.Column(db.Boolean, nullable=True)
    countHearingDisease = db.Column(db.Integer, nullable=True)
    healthProblem = db.Column(db.Boolean, nullable=True)
    descriptionHealthProblem = db.Column(db.String, nullable=True)
    surveyAnswer = db.Column(db.String, nullable=True)
    userId = db.Column(db.Integer, db.ForeignKey("user.id"), nullable=False)

    survey = db.relationship("Survey")
    address = db.relationship("Address")


class Results(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    result = db.Column(db.Integer, nullable=True)
    gender = db.Column(db.String, nullable=True)
    surveyId = db.Column(db.Integer, db.ForeignKey("survey.id"), nullable=False)
    age = db.Column(db.Integer, nullable=True)


#
# class Sixteen(db.Model):
#     id = db.Column(db.Integer, primary_key=True)
#     result = db.Column(db.Integer, nullable=True)
#     surveyId = db.Column(db.Integer, db.ForeignKey("survey.id"), nullable=False)
#     gender = db.Column(db.String, nullable=True)
#
#
# class Seventeen(db.Model):
#     id = db.Column(db.Integer, primary_key=True)
#     result = db.Column(db.Integer, nullable=True)
#     surveyId = db.Column(db.Integer, db.ForeignKey("survey.id"), nullable=False)
#     gender = db.Column(db.String, nullable=True)
#
#
# class Eighteen(db.Model):
#     id = db.Column(db.Integer, primary_key=True)
#     result = db.Column(db.Integer, nullable=True)
#     surveyId = db.Column(db.Integer, db.ForeignKey("survey.id"), nullable=False)
#     gender = db.Column(db.String, nullable=True)
#
#
# class Nineteen(db.Model):
#     id = db.Column(db.Integer, primary_key=True)
#     result = db.Column(db.Integer, nullable=True)
#     surveyId = db.Column(db.Integer, db.ForeignKey("survey.id"), nullable=False)
#     gender = db.Column(db.String, nullable=True)
#
#
# class Twenty(db.Model):
#     id = db.Column(db.Integer, primary_key=True)
#     result = db.Column(db.Integer, nullable=True)
#     surveyId = db.Column(db.Integer, db.ForeignKey("survey.id"), nullable=False)
#     gender = db.Column(db.String, nullable=True)
#
#
# class Twentyone(db.Model):
#     id = db.Column(db.Integer, primary_key=True)
#     result = db.Column(db.Integer, nullable=True)
#     surveyId = db.Column(db.Integer, db.ForeignKey("survey.id"), nullable=False)
#     gender = db.Column(db.String, nullable=True)
#
#
# class Twentytwo(db.Model):
#     id = db.Column(db.Integer, primary_key=True)
#     result = db.Column(db.Integer, nullable=True)
#     surveyId = db.Column(db.Integer, db.ForeignKey("survey.id"), nullable=False)
#     gender = db.Column(db.String, nullable=True)
#
#
# class Twentythree(db.Model):
#     id = db.Column(db.Integer, primary_key=True)
#     result = db.Column(db.Integer, nullable=True)
#     surveyId = db.Column(db.Integer, db.ForeignKey("survey.id"), nullable=False)
#     gender = db.Column(db.String, nullable=True)
#
#
# class Twentyfour(db.Model):
#     id = db.Column(db.Integer, primary_key=True)
#     result = db.Column(db.Integer, nullable=True)
#     surveyId = db.Column(db.Integer, db.ForeignKey("survey.id"), nullable=False)
#     gender = db.Column(db.String, nullable=True)
#
#
# class Twentyfive(db.Model):
#     id = db.Column(db.Integer, primary_key=True)
#     result = db.Column(db.Integer, nullable=True)
#     surveyId = db.Column(db.Integer, db.ForeignKey("survey.id"), nullable=False)
#     gender = db.Column(db.String, nullable=True)
#
#
# class Twentysix(db.Model):
#     id = db.Column(db.Integer, primary_key=True)
#     result = db.Column(db.Integer, nullable=True)
#     surveyId = db.Column(db.Integer, db.ForeignKey("survey.id"), nullable=False)
#     gender = db.Column(db.String, nullable=True)
#
#
# class Twentyseven(db.Model):
#     id = db.Column(db.Integer, primary_key=True)
#     result = db.Column(db.Integer, nullable=True)
#     surveyId = db.Column(db.Integer, db.ForeignKey("survey.id"), nullable=False)
#     gender = db.Column(db.String, nullable=True)
#
#
# class Twentyeight(db.Model):
#     id = db.Column(db.Integer, primary_key=True)
#     result = db.Column(db.Integer, nullable=True)
#     surveyId = db.Column(db.Integer, db.ForeignKey("survey.id"), nullable=False)
#     gender = db.Column(db.String, nullable=True)
#
#
# class Twentynine(db.Model):
#     id = db.Column(db.Integer, primary_key=True)
#     result = db.Column(db.Integer, nullable=True)
#     surveyId = db.Column(db.Integer, db.ForeignKey("survey.id"), nullable=False)
#     gender = db.Column(db.String, nullable=True)
#
#
# class Thirty(db.Model):
#     id = db.Column(db.Integer, primary_key=True)
#     result = db.Column(db.Integer, nullable=True)
#     surveyId = db.Column(db.Integer, db.ForeignKey("survey.id"), nullable=False)
#     gender = db.Column(db.String, nullable=True)
